language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://znonthedev.github.io/travel-uber-ng9/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/travel-uber-ng9/
  on:
    branch: master
